in:
  type: mysql
  host: mysql-source
  port: 3306
  user: root
  password: ""
  database: embulk_test
  table: users

filters:
  - type: hash
    columns:
      - {name: name, algorythm: SHA_256}

out:
  type: mysql
  host: mysql-dest
  port: 3306
  user: root
  password: ""
  database: embulk_test
  table: users
  mode: insert_direct
